### ISSUE TITLE
How to stop on state and wait for event?

### ISSUE THREAD

**Issue by EasonPai** [burrows/statechart.js#14]
Thanks for providing this great library.

I am wondering how to stop on state and wait for event?

Given an example and output :

        let root, a, b, c, d ,e;
        root = new State('root');
        a = new State('a');
        b = new State('b');
        c = new State('c');
        d = new State('d');
        e = new State('e');

        root.addSubstate(a);
        a.addSubstate(b);
        b.addSubstate(c);
        c.addSubstate(d);
        d.addSubstate(e);

        root.goto('/a/b/c'); //   ["/a/b/c/d/e"]

Once when root state began, it goes all the way down to state 'e'.

What I need is to stop on certain state, say 'c',
so I can process some business logic related to 'c' via enter method, 
and send event to go on to next state when my c-process is done.

**Comment by burrows** [comment]
The current state of a statechart can never be just a parent state. Once a parent state is entered we must enter one of its children.

You have two options here, depending on whether your business logic is synchronous or asynchronous.

If its synchronous, then you can use a condition state to determine which child state to enter:

```javascript
var sc = State.define(function() {
  this.state('a', function() {
    this.C(function() {
      if (shouldGoToB) { return './b'; }
      if (shouldGoToC) { return './c'; }
      if (shouldGoToD) { return './d'; }
    });
    this.state('b');
    this.state('c');
    this.state('d');
  });
});
```

Otherwise, if the logic you need to perform is asynchronous, you'll need to make the state a leaf state, perform the async action in its `enter` handler and send an event that triggers a transition to some sibling state:

```javascript
var sc = State.define(function() {
  this.state('a', function() {
    this.enter(function() {
      doSomeAsyncAction(function(result) {
        if (result.b) {
          sc.send('eventB');
        }
        else {
          sc.send('eventC');
        }
      });
    });

    this.event('eventB', function() {
      this.goto('../b');
    });

    this.event('eventC', function() {
      this.goto('../c');
    });
  });

  this.state('b');

  this.state('c');
});
```

**Comment by EasonPai** [comment]
I see I totally mis-understood the idea,
now everything works fine, its really fun to play with it!

Thanks for the explanations.
